language: python

python:
  - "3.6"
    
services:
  - docker
env:
  - LC_ALL C.UTF-8
  - LANG C.UTF-8
  - DISPLAY=$DISPLAY
  
volumes:
  - /tmp/.X11-unix:/tmp/.X11-unix 
      
before_script: pip install docker-compose

install:  
  - "pip install pytest"
  - docker-compose up
  
script: 
   - python -m pytest tests/ -v
 
