language: python

python:
  - "3.6"
    
services:
  - docker
env:
  - DISPLAY=$DISPLAY
      
before_script: pip install docker-compose

install:  
  - "pip install pytest"
  - "pip install pyqt5"
  #- docker-compose up
  
script: 
   - python -m pytest tests/ -v
 
