language: python
python:
  - "3.8"
  - "nightly"
  
services:
  - docker

before_install:
  - docker-compose up

install:
  - "pip install pyqt5"
  - "pip install pytest"
  - "pip install -r requirements.txt"
  - apt update &&                  \
    apt upgrade -y &&              \
    apt dist-upgrade -y &&         \
    apt install -y                 \
        git                        \
        wget                       \
        xvfb                       \
        flex                       \
        dh-make                    \
        debhelper                  \
        checkinstall               \
        fuse                       \
        snapcraft                  \
        bison                      \
        libxcursor-dev             \
        libxcomposite-dev          \
        software-properties-common \
        build-essential            \
        libssl-dev                 \
        libxcb1-dev                \
        libx11-dev                 \
        libgl1-mesa-dev            \
        libudev-dev                \
        python3.8                  \
        python3-pyqt5              \
        python3-pip                \
        python3-psycopg2           \
        python3-requests           \
script: python -m pytest tests/ -v
 
