language: python
python:
  - "3.8"
  - "nightly"
  
services:
  - docker

before_install:
  - docker-compose up

install:
  - "pip install pytest"
  - "pip install -r requirements.txt"
script: python -m pytest tests/ -v
 
