language: python

python:
  - "3.8"
    
services:
  - docker
env:
  - LC_ALL C.UTF-8
  - LANG C.UTF-8

install:
  - "pip install pyqt5"
  - "pip install pytest"
  - docker-compose up
  
script: python -m pytest tests/ -v
 
