language: python

python:
  - "3.8"
  - "nightly"
  
services:
  - docker
env:
  - LC_ALL C.UTF-8
  - LANG C.UTF-8

before_install:
  - sudo apt-add-repository ppa:beineri/opt-qt551 -y
  - adduser --quiet --disabled-password qtuser
  - sudo rm /bin/sh && ln -s /bin/bash /bin/sh
  - sudo apt update &&                  \
    apt upgrade -y &&              \
    apt dist-upgrade -y &&         \
    apt install -y                 \
        git                        \
        wget                       \
        xvfb                       \
        flex                       \
        dh-make                    \
        debhelper                  \
        checkinstall               \
        fuse                       \
        snapcraft                  \
        bison                      \
        libxcursor-dev             \
        libxcomposite-dev          \
        software-properties-common \
        build-essential            \
        libssl-dev                 \
        libxcb1-dev                \
        libx11-dev                 \
        libgl1-mesa-dev            \
        libudev-dev                \
        python3.8                  \
        python3-pyqt5              \
        python3-pip                \
        python3-psycopg2           \
        python3-requests           \
        nano                     &&\
    apt clean

install:
  - "pip install pyqt5"
  - "pip install pytest"
  - "pip install -r requirements.txt"  
  - docker-compose up
  
script: python -m pytest tests/ -v
 
