language: python

python:
  - "3.6"
    
services:
  - docker
env:
  - LC_ALL C.UTF-8
  - LANG C.UTF-8
before_script: pip install docker-compose

install:  
  - "pip install pytest"
 
  
script: 
  - docker-compose run app sh -c "python -m pytest tests/ -v"
 
